/**
 * Generate docs/design/theme.css from docs/design/tokens.json.
 *
 * tokens.json is the source of truth for every visual value (CLAUDE.md: "Styling: only CSS
 * variables from docs/design/theme.css (generated from tokens.json; never hand-edit it)").
 * Run after changing a token:
 *
 *   node scripts/tokens-export.mjs
 *   node scripts/tokens-export.mjs --check   # exit 1 if theme.css is stale (for CI)
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(root, 'docs/design/tokens.json')
const OUT = join(root, 'docs/design/theme.css')

/** token group -> CSS custom-property prefix. `null` means the key is the whole name. */
const PREFIX = {
  color: '--color-',
  font: '--font-',
  size: '--text-',
  line: '--leading-',
  space: '--space-',
  radius: '--radius-',
  edge: '--edge-',
  breakpoint: '--bp-',
  alias: '--',
}

/** motion is the one group whose keys don't share a prefix. */
const MOTION = {
  fast: '--duration-fast',
  base: '--duration-base',
  draw: '--duration-draw',
  fly: '--duration-fly',
  easing: '--ease',
}

/** Emitted inside `@media (min-width: breakpoint.lg)` rather than on :root. */
const RESPONSIVE = { 'size-lg': '--text-', 'line-lg': '--leading-' }

const isToken = (v) => v && typeof v === 'object' && '$value' in v

function declarations(group, prefix) {
  return Object.entries(group ?? {})
    .filter(([, v]) => isToken(v))
    .map(([key, { $value }]) => `  ${prefix}${key}: ${$value};`)
}

function build(tokens) {
  const lines = [
    '/* Generated by scripts/tokens-export.mjs from docs/design/tokens.json.',
    ' * Edit tokens.json and re-run the script; never hand-edit this file.',
    ` * ${tokens.meta.project} · ${tokens.meta.status} · ${tokens.meta.updated} */`,
    ':root {',
    '  color-scheme: light;',
  ]

  for (const [group, prefix] of Object.entries(PREFIX)) {
    lines.push(...declarations(tokens[group], prefix))
  }
  for (const [key, name] of Object.entries(MOTION)) {
    if (isToken(tokens.motion?.[key])) lines.push(`  ${name}: ${tokens.motion[key].$value};`)
  }
  lines.push('}')

  const responsive = Object.entries(RESPONSIVE).flatMap(([group, prefix]) =>
    declarations(tokens[group], prefix),
  )
  if (responsive.length) {
    lines.push('', `@media (min-width: ${tokens.breakpoint.lg.$value}) {`, '  :root {')
    lines.push(...responsive.map((d) => `  ${d}`))
    lines.push('  }', '}')
  }

  return lines.join('\n') + '\n'
}

const css = build(JSON.parse(readFileSync(SRC, 'utf8')))

if (process.argv.includes('--check')) {
  // Compare content, not line endings: a Windows checkout (core.autocrlf=true) holds CRLF on disk
  // while this script emits LF, which is not a stale file.
  const normalise = (text) => text.replace(/\r\n/g, '\n')
  if (normalise(readFileSync(OUT, 'utf8')) !== normalise(css)) {
    console.error('theme.css is out of date. Run: node scripts/tokens-export.mjs')
    process.exit(1)
  }
  console.log('theme.css is up to date.')
} else {
  writeFileSync(OUT, css)
  console.log(`Wrote ${OUT}`)
}
